# Generated by Django 5.0.1 on 2024-01-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='connect_with_room',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
