# Generated by Django 4.2.9 on 2024-02-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_client_connect_with_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cl_ip_add',
            field=models.GenericIPAddressField(default=0),
            preserve_default=False,
        ),
    ]
