# Generated by Django 5.2.15 on 2026-06-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_client_cl_ip_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='room',
            name='model_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
