# Generated by Django 5.2.15 on 2026-06-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0009_room_description_room_title_alter_room_model_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
        migrations.AlterField(
            model_name='room',
            name='model_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
