# Generated by Django 5.2.16 on 2026-08-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0011_room_description_room_title_alter_room_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='model_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
