"""
Django settings for webserver project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
# import websockets
# import redis
# from django.core.cache.backends.redis import RedisCache

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

def _env_list(name):
    return [v.strip() for v in os.environ.get(name, '').split(',') if v.strip()]


# A development key is generated on the fly when DJANGO_SECRET_KEY is unset, so
# no usable key is ever committed. It changes on every restart, which logs
# everyone out -- set the variable for anything longer-lived than a test run.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    from django.core.management.utils import get_random_secret_key
    SECRET_KEY = get_random_secret_key()

# Off unless asked for: DEBUG serves tracebacks, including settings values, to
# whoever triggers the error.
DEBUG = os.environ.get('DJANGO_DEBUG', '').lower() in ('1', 'true', 'yes', 'on')

# Hosts this server answers for. Defaults to local access only; add the name the
# demo is reached under, e.g. DJANGO_ALLOWED_HOSTS=demo.example.org
ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS') or ['localhost', '127.0.0.1', '[::1]']

# Only needed for POSTs (admin login, room and model management) over HTTPS.
# Include the scheme and the port, e.g. https://demo.example.org:8000 -- an
# entry without the port does not match a request served on 8000.
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

# Signaling WebSocket location, as handed to the browser.
#
# Override only when signaling runs on a host that already has a trusted
# certificate. SIGNALING_WS_URL is a full URL where '{room}' is substituted,
# e.g. 'wss://signaling.example.org/ws/connection/{room}/'. SIGNALING_WS_PORT
# is the simpler "same host, different port" case, e.g. '8001'.
SIGNALING_WS_URL = os.environ.get('SIGNALING_WS_URL', '')
SIGNALING_WS_PORT = os.environ.get('SIGNALING_WS_PORT', '')

import mimetypes
mimetypes.add_type("application/javascript", ".js", True)
mimetypes.add_type("application/octet-stream", ".onnx", True)

# Application definition

INSTALLED_APPS = [
    'daphne',
    'connection.apps.ConnectionConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'sslserver',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# STORAGES = {
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
#     },
# }

# Models are uploaded at runtime into connection/static/, so the server has to
# serve files that did not exist when it started. Without the finders, every
# upload would need a collectstatic run and a restart to become reachable.
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

ROOT_URLCONF = 'webserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webserver.wsgi.application'

ASGI_APPLICATION = 'webserver.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            # socket_timeout must stay comfortably above channels_redis's
            # brpop_timeout (5 s), or idle rooms drop their WebSocket every
            # few seconds.
            'hosts': [{
                'host': '127.0.0.1',
                'port': 6379,
                'socket_timeout': 30,
                'socket_connect_timeout': 5,
                # Detect connections dropped by an idle-timeout in between.
                'health_check_interval': 30,
            }],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# AUTHENTICATION_BACKENDS = [
#    "django.contrib.auth.backends.ModelBackend",
#    "sesame.backends.ModelBackend",
# ]

# SESAME_MAX_AGE = 30

# CACHES = {
#    "default": {
#        "BACKEND": "django_redis.cache.RedisCache",
#        "LOCATION": "redis://127.0.0.1:6379/1",
#    }
# }

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Paris' #'CET'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = 'media/model/'

STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATIC_ROOT = "/webserver/connection/static/"
MEDIA_ROOT = "/webserver/connection/media/model"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cookie and redirect hardening, off by default because the demo is routinely
# run over http://localhost, where secure cookies are never sent back.
SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', '').lower() in ('1', 'true', 'yes', 'on')
SESSION_COOKIE_SECURE = os.environ.get('DJANGO_SECURE_COOKIES', '').lower() in ('1', 'true', 'yes', 'on')
CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE

# Only when a trusted reverse proxy sets the header. Enabling it without one
# lets any client claim its request arrived over HTTPS.
if os.environ.get('DJANGO_TRUST_PROXY_SSL_HEADER', '').lower() in ('1', 'true', 'yes', 'on'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# subjectAltName
